#!/usr/bin/env node
// fixpoint loop: type checker derives ready steps, runner executes and
// feeds done facts back until nothing is ready
import { execFileSync } from "node:child_process";
import { appendFileSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const DONE_JSON = join(HERE, "done.json");
const DONE_TS = join(HERE, "done.ts");
const LOG = join(HERE, "log.txt");

const EFFECTS = {
  fetch: () => log("fetched sources"),
  build: () => log(`built at ${new Date().toISOString()}`),
  test: () => log(`tests green under tsgo ${run("npx", ["tsgo", "--version"])}`),
  deploy: () => log(`deployed rev ${run("git", ["rev-parse", "--short", "HEAD"])}`),
};

function run(cmd, args) {
  return execFileSync(cmd, args, { encoding: "utf8" }).trim();
}

function log(line) {
  appendFileSync(LOG, `${line}\n`);
  console.log(`  effect: ${line}`);
}

function loadDone() {
  return existsSync(DONE_JSON) ? JSON.parse(readFileSync(DONE_JSON, "utf8")) : [];
}

function saveDone(done) {
  writeFileSync(DONE_JSON, JSON.stringify(done, null, 2) + "\n");
  const entries = done.map((s) => `  "done(${s})",`).join("\n");
  writeFileSync(
    DONE_TS,
    "// generated by loop/run.mjs from loop/done.json; do not edit by hand\n" +
      (done.length
        ? `export type Done = [\n${entries}\n];\n`
        : "export type Done = [];\n"),
  );
}

function ready() {
  const out = run("node", [join(HERE, "..", "tools", "print-type.mjs"), join(HERE, "program.ts"), "Out"]);
  return JSON.parse(out).map((answer) => answer[1]);
}

const done = loadDone();
saveDone(done);
for (let cycle = 1; cycle <= 10; cycle++) {
  const frontier = ready();
  if (frontier.length === 0) {
    console.log(`cycle ${cycle}: fixpoint, nothing ready`);
    break;
  }
  const step = frontier[0];
  console.log(`cycle ${cycle}: checker derived ready(${step})`);
  EFFECTS[step]();
  done.push(step);
  saveDone(done);
}
